name: AndroidBuild
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '18'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build

#      - name: Run unit tests
#        run: ./gradlew test
#
#      - name: Run lint
#        run: ./gradlew ktlintFormat detekt ktlintCheck

#      - name: SonarQube Scan
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: ./gradlew sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KotlinCICD.apk
          path: app/build/outputs/apk/debug/app-debug.apk

