name: AndroidBuild
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '18'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
            api-level: 30
            build-tools: 30.0.3

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > ./local.properties

      - name: Run lint
        run: ./gradlew ktlintFormat lint detekt ktlintCheck

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#      - name: Run unit tests, jacoco
#        run: ./gradlew test jacocoTestReport
#
#      - name: SonarQube Scan
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: http://localhost:9000
#          SONAR_PROJECT_KEY: KotlinCICDPractice
#          SONAR_ORGANIZATION: KotlinCICDPractice
#          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
#        run: ./gradlew sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=318109bb61c534e7a847069ad286b3845dd5b0fb

#      - name: Build with Gradle
#        run: ./gradlew build

#      - name: Upload a Build Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: KotlinCICD.apk
#          path: app/build/outputs/apk/debug/app-debug.apk

