name: AndroidBuild
on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Manual Debug Build'
        description: 'Release Notes'
  pull_request:
    branches-ignore:
      - main
      - develop

jobs:
  pr-setup-lint-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '18'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 30
          build-tools: 30.0.3

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > ./local.properties

      - name: Run lint
        run: ./gradlew ktlintFormat lint detekt ktlintCheck

      - name: Run unit tests, jacoco
        run: ./gradlew test
#        jacocoPrDevDebugTestReport

      - name: SonarQube Scan
        run: ./gradlew sonar -Dsonar.host.url=https://52a9-103-249-234-193.ngrok-free.app -Dsonar.login=${{ secrets.SONAR_LOGIN }} -Dsonar.password=${{ secrets.SONAR_PASSWORD }} --stacktrace

      - name: Build with Gradle
        run: ./gradlew assembleDevDebug
